import { en, TranslationKey } from './en';

type Dict = Partial<Record<TranslationKey, string>>;
const base: Dict = { ...en };

const common = (language: string, labels: Record<string, string>): Dict => ({
  ...base,
  'language.title': labels.title, 'language.subtitle': labels.subtitle,
  'language.english': labels.english, 'language.tamil': labels.tamil, 'language.hindi': labels.hindi,
  'language.telugu': labels.telugu, 'language.malayalam': labels.malayalam, 'language.kannada': labels.kannada,
  'nav.home': labels.home, 'nav.report': labels.report, 'nav.nearby': labels.nearby, 'nav.profile': labels.profile,
  'nav.hotspots': labels.hotspots, 'nav.reports': labels.reports, 'nav.projects': labels.projects, 'nav.budget': labels.budget,
  'home.citizen': labels.citizen, 'home.quickReport': labels.quick, 'home.viewAll': labels.all, 'home.recentActivity': labels.recent,
  'home.heroAction': labels.report, 'home.emptyTitle': labels.empty, 'home.emptyAction': labels.start,
  'newComplaint.title': labels.report, 'newComplaint.submit': labels.submit, 'newComplaint.modeText': labels.text,
  'newComplaint.modeVoice': labels.voice, 'newComplaint.modePhoto': labels.photo, 'newComplaint.locationCaptured': labels.location,
  'menu.language': labels.language, 'menu.logOut': labels.logout, 'profile.title': labels.profile,
  'profile.language': labels.language, 'profile.citizen': labels.citizen, 'profile.authority': labels.authority,
  'common.cancel': labels.cancel, 'common.skip': labels.skip, 'common.loading': labels.loading,
  'common.list': labels.list, 'common.map': labels.map, 'common.location': labels.location,
  'common.text': labels.text, 'common.voice': labels.voice, 'common.photo': labels.photo,
  'common.reports': labels.reports, 'common.report': labels.report, 'common.people': labels.people,
  'nearby.title': labels.nearby, 'nearby.reports': labels.reports, 'hotspots.title': labels.hotspots,
  'reports.title': labels.reports, 'projects.title': labels.projects, 'budget.title': labels.budget,
  'map.loading': labels.loading,
  'newComplaint.voiceIdle': labels.voiceIdle,
});

export const bn = common('bn', { title: 'অ্যাপের ভাষা', subtitle: 'পুরো অ্যাপের জন্য ভাষা বেছে নিন।', english: 'English (ইংরেজি)', tamil: 'தமிழ் (তামিল)', hindi: 'हिन्दी (হিন্দি)', telugu: 'తెలుగు (তেলুগু)', malayalam: 'മലയാളം (মালয়ালম)', kannada: 'ಕನ್ನಡ (কন্নড়)', home: 'হোম', report: 'রিপোর্ট', nearby: 'কাছাকাছি', profile: 'প্রোফাইল', hotspots: 'হটস্পট', reports: 'রিপোর্ট', projects: 'প্রকল্প', budget: 'বাজেট', citizen: 'নাগরিক', quick: 'দ্রুত রিপোর্ট', all: 'সব দেখুন', recent: 'সাম্প্রতিক কার্যকলাপ', empty: 'এখনও কোনো রিপোর্ট নেই', start: 'শুরু করুন', submit: 'রিপোর্ট জমা দিন', text: 'টেক্সট', voice: 'ভয়েস', photo: 'ছবি', location: 'অবস্থান', language: 'ভাষা', logout: 'লগ আউট', authority: 'কর্তৃপক্ষ', cancel: 'বাতিল', skip: 'এড়িয়ে যান', loading: 'লোড হচ্ছে…', list: 'তালিকা', map: 'মানচিত্র', people: 'মানুষ', voiceIdle: 'রেকর্ড করতে ট্যাপ করুন। বাংলা, তামিল বা ইংরেজিতে কথা বলুন।' });
export const mr = common('mr', { title: 'अॅपची भाषा', subtitle: 'संपूर्ण अॅपसाठी भाषा निवडा.', english: 'English (इंग्रजी)', tamil: 'தமிழ் (तमिळ)', hindi: 'हिन्दी', telugu: 'తెలుగు (तेलुगू)', malayalam: 'മലയാളം (मल्याळम)', kannada: 'ಕನ್ನಡ (कन्नड)', home: 'होम', report: 'अहवाल', nearby: 'जवळपास', profile: 'प्रोफाइल', hotspots: 'हॉटस्पॉट', reports: 'अहवाल', projects: 'प्रकल्प', budget: 'अर्थसंकल्प', citizen: 'नागरिक', quick: 'जलद अहवाल', all: 'सर्व पहा', recent: 'अलीकडील क्रिया', empty: 'अजून अहवाल नाहीत', start: 'सुरुवात करा', submit: 'अहवाल पाठवा', text: 'मजकूर', voice: 'आवाज', photo: 'फोटो', location: 'स्थान', language: 'भाषा', logout: 'लॉग आउट', authority: 'प्राधिकरण', cancel: 'रद्द करा', skip: 'वगळा', loading: 'लोड होत आहे…', list: 'यादी', map: 'नकाशा', people: 'लोक', voiceIdle: 'रेकॉर्ड करण्यासाठी टॅप करा। मराठी, तमिळ किंवा इंग्रजीत बोला.' });
export const gu = common('gu', { title: 'એપની ભાષા', subtitle: 'આખી એપ માટે ભાષા પસંદ કરો.', english: 'English (અંગ્રેજી)', tamil: 'தமிழ் (તમિલ)', hindi: 'हिन्दी (હિન્દી)', telugu: 'తెలుగు (તેલુગુ)', malayalam: 'മലയാളം (મલયાલમ)', kannada: 'ಕನ್ನಡ (કન્નડ)', home: 'હોમ', report: 'રિપોર્ટ', nearby: 'નજીકમાં', profile: 'પ્રોફાઇલ', hotspots: 'હોટસ્પોટ', reports: 'રિપોર્ટ', projects: 'પ્રોજેક્ટ્સ', budget: 'બજેટ', citizen: 'નાગરિક', quick: 'ઝડપી રિપોર્ટ', all: 'બધું જુઓ', recent: 'તાજેતરની પ્રવૃત્તિ', empty: 'હજુ કોઈ રિપોર્ટ નથી', start: 'શરૂ કરો', submit: 'રિપોર્ટ સબમિટ કરો', text: 'ટેક્સ્ટ', voice: 'વૉઇસ', photo: 'ફોટો', location: 'સ્થાન', language: 'ભાષા', logout: 'લૉગ આઉટ', authority: 'સત્તાધિકારી', cancel: 'રદ કરો', skip: 'છોડો', loading: 'લોડ થઈ રહ્યું છે…', list: 'યાદી', map: 'નકશો', people: 'લોકો', voiceIdle: 'રેકોર્ડ કરવા ટેપ કરો. ગુજરાતી, તમિલ અથવા અંગ્રેજીમાં બોલો.' });
export const pa = common('pa', { title: 'ਐਪ ਦੀ ਭਾਸ਼ਾ', subtitle: 'ਪੂਰੀ ਐਪ ਲਈ ਭਾਸ਼ਾ ਚੁਣੋ।', english: 'English (ਅੰਗਰੇਜ਼ੀ)', tamil: 'தமிழ் (ਤਮਿਲ)', hindi: 'हिन्दी (ਹਿੰਦੀ)', telugu: 'తెలుగు (ਤੇਲਗੂ)', malayalam: 'മലയാളം (ਮਲਿਆਲਮ)', kannada: 'ಕನ್ನಡ (ਕੰਨੜ)', home: 'ਹੋਮ', report: 'ਰਿਪੋਰਟ', nearby: 'ਨੇੜੇ', profile: 'ਪ੍ਰੋਫਾਈਲ', hotspots: 'ਹੌਟਸਪੌਟ', reports: 'ਰਿਪੋਰਟਾਂ', projects: 'ਪ੍ਰੋਜੈਕਟ', budget: 'ਬਜਟ', citizen: 'ਨਾਗਰਿਕ', quick: 'ਤੁਰੰਤ ਰਿਪੋਰਟ', all: 'ਸਭ ਦੇਖੋ', recent: 'ਹਾਲੀਆ ਗਤੀਵਿਧੀ', empty: 'ਹਾਲੇ ਕੋਈ ਰਿਪੋਰਟ ਨਹੀਂ', start: 'ਸ਼ੁਰੂ ਕਰੋ', submit: 'ਰਿਪੋਰਟ ਜਮ੍ਹਾਂ ਕਰੋ', text: 'ਲਿਖਤ', voice: 'ਆਵਾਜ਼', photo: 'ਫੋਟੋ', location: 'ਟਿਕਾਣਾ', language: 'ਭਾਸ਼ਾ', logout: 'ਲੌਗ ਆਊਟ', authority: 'ਅਧਿਕਾਰੀ', cancel: 'ਰੱਦ ਕਰੋ', skip: 'ਛੱਡੋ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…', list: 'ਸੂਚੀ', map: 'ਨਕਸ਼ਾ', people: 'ਲੋਕ', voiceIdle: 'ਰਿਕਾਰਡ ਕਰਨ ਲਈ ਟੈਪ ਕਰੋ। ਪੰਜਾਬੀ, ਤਮਿਲ ਜਾਂ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਬੋਲੋ।' });
export const or = common('or', { title: 'ଆପ୍ ଭାଷା', subtitle: 'ସମ୍ପୂର୍ଣ୍ଣ ଆପ୍ ପାଇଁ ଭାଷା ବାଛନ୍ତୁ।', english: 'English (ଇଂରାଜୀ)', tamil: 'தமிழ் (ତାମିଲ)', hindi: 'हिन्दी (ହିନ୍ଦୀ)', telugu: 'తెలుగు (ତେଲୁଗୁ)', malayalam: 'മലയാളം (ମାଲାୟାଲମ୍)', kannada: 'ಕನ್ನಡ (କନ୍ନଡ)', home: 'ହୋମ୍', report: 'ରିପୋର୍ଟ', nearby: 'ନିକଟରେ', profile: 'ପ୍ରୋଫାଇଲ୍', hotspots: 'ହଟସ୍ପଟ୍', reports: 'ରିପୋର୍ଟ', projects: 'ପ୍ରକଳ୍ପ', budget: 'ବଜେଟ୍', citizen: 'ନାଗରିକ', quick: 'ତୁରନ୍ତ ରିପୋର୍ଟ', all: 'ସବୁ ଦେଖନ୍ତୁ', recent: 'ସାମ୍ପ୍ରତିକ କାର୍ଯ୍ୟକଳାପ', empty: 'ଏପର୍ଯ୍ୟନ୍ତ ରିପୋର୍ଟ ନାହିଁ', start: 'ଆରମ୍ଭ କରନ୍ତୁ', submit: 'ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ', text: 'ଟେକ୍ସଟ୍', voice: 'ସ୍ୱର', photo: 'ଫଟୋ', location: 'ସ୍ଥାନ', language: 'ଭାଷା', logout: 'ଲଗ୍ ଆଉଟ୍', authority: 'କର୍ତ୍ତୃପକ୍ଷ', cancel: 'ବାତିଲ୍', skip: 'ଛାଡ଼ନ୍ତୁ', loading: 'ଲୋଡ୍ ହେଉଛି…', list: 'ତାଲିକା', map: 'ମାନଚିତ୍ର', people: 'ଲୋକ', voiceIdle: 'ରେକର୍ଡ କରିବାକୁ ଟ୍ୟାପ୍ କରନ୍ତୁ। ଓଡ଼ିଆ, ତାମିଲ୍ କିମ୍ବା ଇଂରାଜୀରେ କୁହନ୍ତୁ।' });
export const as = common('as', { title: 'এপৰ ভাষা', subtitle: 'সম্পূৰ্ণ এপৰ বাবে ভাষা বাছক।', english: 'English (ইংৰাজী)', tamil: 'தமிழ் (তামিল)', hindi: 'हिन्दी (হিন্দী)', telugu: 'తెలుగు (তেলুগু)', malayalam: 'മലയാളം (মালয়ালম)', kannada: 'ಕನ್ನಡ (কন্নড়)', home: 'হোম', report: 'ৰিপ’ৰ্ট', nearby: 'ওচৰত', profile: 'প্ৰফাইল', hotspots: 'হটস্পট', reports: 'ৰিপ’ৰ্ট', projects: 'প্ৰকল্প', budget: 'বাজেট', citizen: 'নাগৰিক', quick: 'দ্ৰুত ৰিপ’ৰ্ট', all: 'সকলো চাওক', recent: 'শেহতীয়া কাৰ্যকলাপ', empty: 'এতিয়ালৈ কোনো ৰিপ’ৰ্ট নাই', start: 'আৰম্ভ কৰক', submit: 'ৰিপ’ৰ্ট জমা দিয়ক', text: 'টেক্সট', voice: 'কণ্ঠ', photo: 'ফটো', location: 'স্থান', language: 'ভাষা', logout: 'লগ আউট', authority: 'কৰ্তৃপক্ষ', cancel: 'বাতিল', skip: 'এৰক', loading: 'লোড হৈ আছে…', list: 'তালিকা', map: 'মানচিত্ৰ', people: 'মানুহ', voiceIdle: 'ৰেকৰ্ড কৰিবলৈ টেপ কৰক। অসমীয়া, তামিল বা ইংৰাজীত কথা কওক।' });
export const ur = common('ur', { title: 'ایپ کی زبان', subtitle: 'پوری ایپ کے لیے زبان منتخب کریں۔', english: 'English (انگریزی)', tamil: 'தமிழ் (تمل)', hindi: 'हिन्दी (ہندی)', telugu: 'తెలుగు (تیلگو)', malayalam: 'മലയാളം (ملیالم)', kannada: 'ಕನ್ನಡ (کنڑ)', home: 'ہوم', report: 'رپورٹ', nearby: 'قریب', profile: 'پروفائل', hotspots: 'ہاٹ اسپاٹس', reports: 'رپورٹس', projects: 'منصوبے', budget: 'بجٹ', citizen: 'شہری', quick: 'فوری رپورٹ', all: 'سب دیکھیں', recent: 'حالیہ سرگرمی', empty: 'ابھی کوئی رپورٹ نہیں', start: 'شروع کریں', submit: 'رپورٹ جمع کریں', text: 'متن', voice: 'آواز', photo: 'تصویر', location: 'مقام', language: 'زبان', logout: 'لاگ آؤٹ', authority: 'اختیار', cancel: 'منسوخ', skip: 'چھوڑیں', loading: 'لوڈ ہو رہا ہے…', list: 'فہرست', map: 'نقشہ', people: 'لوگ', voiceIdle: 'ریکارڈ کرنے کے لیے ٹیپ کریں۔ اردو، تمل یا انگریزی میں بولیں۔' });
