/** Kannada translations for the application dictionary. */
import { ml } from './ml';
import { TranslationKey } from './en';

export const kn: Partial<Record<TranslationKey, string>> = {
  ...ml,
  'common.cancel': 'ರದ್ದುಮಾಡಿ', 'common.retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ', 'common.skip': 'ಬಿಟ್ಟುಬಿಡಿ', 'common.loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ…', 'common.required': 'ಅಗತ್ಯ', 'common.optional': 'ಐಚ್ಛಿಕ',
  'login.welcomeBack': 'ಮತ್ತೆ ಸ್ವಾಗತ', 'login.subtitle': 'ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಲು ಮತ್ತು ನಿಮ್ಮ ನಗರದಲ್ಲಿ ನಡೆಯುತ್ತಿರುವ ಬದಲಾವಣೆಗಳನ್ನು ತಿಳಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.', 'login.phoneOrEmail': 'ಫೋನ್ ಅಥವಾ ಇಮೇಲ್', 'login.password': 'ಪಾಸ್‌ವರ್ಡ್', 'login.signIn': 'ಸೈನ್ ಇನ್ ಮಾಡಿ', 'login.newHere': 'ಇಲ್ಲಿ ಹೊಸಬರೇ?', 'login.createAccount': 'ಖಾತೆ ರಚಿಸಿ', 'login.errEmpty': 'ನಿಮ್ಮ ಫೋನ್/ಇಮೇಲ್ ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ.', 'login.errIncorrect': 'ಫೋನ್/ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್ ತಪ್ಪಾಗಿದೆ.', 'login.errNetwork': 'ಸರ್ವರ್ ಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ನಿಮ್ಮ ಸಂಪರ್ಕ ಪರಿಶೀಲಿಸಿ.',
  'register.title': 'ಖಾತೆ ರಚಿಸಿ', 'register.subtitle': 'UCIPSಗೆ ಸೇರಿ ಏನು ನಿರ್ಮಿಸಬೇಕು ಎಂಬುದನ್ನು ನಿರ್ಧರಿಸಲು ಸಹಾಯ ಮಾಡಿ.', 'register.fullName': 'ಪೂರ್ಣ ಹೆಸರು', 'register.phoneNumber': 'ಫೋನ್ ಸಂಖ್ಯೆ', 'register.aadhaarNumber': 'ಆಧಾರ್ ಸಂಖ್ಯೆ', 'register.aadhaarPlaceholder': 'ಗುರುತಿನ ಪರಿಶೀಲನೆಗಾಗಿ 12 ಅಂಕಿಯ ಆಧಾರ್', 'register.password': 'ಪಾಸ್‌ವರ್ಡ್', 'register.iAmA': 'ನಾನು', 'register.roleCitizen': 'ನಾಗರಿಕ', 'register.roleCitizenDesc': 'ನನ್ನ ಪ್ರದೇಶದ ಸಮಸ್ಯೆಗಳನ್ನು ವರದಿ ಮಾಡಿ', 'register.roleAuthority': 'ಅಧಿಕಾರಿ', 'register.roleAuthorityDesc': 'ಯೋಜನೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಹಣಕಾಸು ಒದಗಿಸಿ', 'register.sendOtp': 'OTP ಕಳುಹಿಸಿ', 'register.alreadyHaveAccount': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?', 'register.signIn': 'ಸೈನ್ ಇನ್ ಮಾಡಿ', 'register.errAllRequired': 'ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳು ಅಗತ್ಯ.', 'register.errPasswordLength': 'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಬೇಕು.', 'register.errAadhaarLength': 'ಆಧಾರ್ ಸಂಖ್ಯೆ 12 ಅಂಕಿಗಳಿರಬೇಕು.', 'register.errConflict': 'ಈ ಫೋನ್, ಇಮೇಲ್ ಅಥವಾ ಆಧಾರ್ ಸಂಖ್ಯೆಯ ಖಾತೆ ಈಗಾಗಲೇ ಇದೆ.', 'register.verifyTitle': 'ನಿಮ್ಮ ಫೋನ್ ಪರಿಶೀಲಿಸಿ', 'register.verifySubtitle': '{phone}ಗೆ ಕಳುಹಿಸಿದ OTP ನಮೂದಿಸಿ.', 'register.demoModeTitle': 'ಡೆಮೊ ಮೋಡ್ — SMS ಕಳುಹಿಸಲಾಗಿಲ್ಲ', 'register.demoModeBody': 'SMS ಸೇವೆ ಸಂಪರ್ಕಗೊಂಡಿಲ್ಲ, ಆದ್ದರಿಂದ ಕೋಡ್ ಅನ್ನು ಇಲ್ಲಿ ತೋರಿಸಲಾಗಿದೆ:', 'register.demoModeFill': 'ತುಂಬಲು ಟ್ಯಾಪ್ ಮಾಡಿ', 'register.otpLabel': '6 ಅಂಕಿಯ OTP', 'register.verifyButton': 'ಪರಿಶೀಲಿಸಿ ಖಾತೆ ರಚಿಸಿ', 'register.didntGetIt': 'ಬಂದಿಲ್ಲವೇ?', 'register.resendOtp': 'OTP ಮತ್ತೆ ಕಳುಹಿಸಿ', 'register.errOtpLength': '6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ.', 'register.otpSentToast': 'OTP ನಿಮ್ಮ ಫೋನ್‌ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ',
  'nav.home': 'ಹೋಮ್', 'nav.report': 'ವರದಿ', 'nav.nearby': 'ಸಮೀಪದಲ್ಲಿ', 'nav.profile': 'ಪ್ರೊಫೈಲ್', 'nav.hotspots': 'ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು', 'nav.reports': 'ವರದಿಗಳು', 'nav.projects': 'ಯೋಜನೆಗಳು', 'nav.budget': 'ಬಜೆಟ್',
  'home.greetingMorning': 'ಶುಭೋದಯ', 'home.greetingAfternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ', 'home.greetingEvening': 'ಶುಭ ಸಂಜೆ', 'home.citizen': 'ನಾಗರಿಕ', 'home.tagline': 'ನಿಮ್ಮ ಧ್ವನಿ. ನಮ್ಮ ಆದ್ಯತೆ. ಉತ್ತಮ ಸಮುದಾಯಗಳು.', 'home.statReports': 'ಸಲ್ಲಿಸಿದ ವರದಿಗಳು', 'home.statHotspots': 'ನಿಮ್ಮ ಸಮೀಪದ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳಲ್ಲಿ', 'home.statResolved': 'ಪರಿಹರಿಸಿದ ಸಮಸ್ಯೆಗಳು', 'home.quickReport': 'ತ್ವರಿತ ವರದಿ', 'home.viewAll': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ', 'home.voiceReport': 'ಧ್ವನಿ\nವರದಿ', 'home.photoReport': 'ಫೋಟೋ\nವರದಿ', 'home.writeReport': 'ಬರಹದ\nವರದಿ', 'home.selectLocation': 'ಸ್ಥಳ\nಆಯ್ಕೆಮಾಡಿ', 'home.heroTitle': 'ವರದಿ ಮಾಡಿ, ಗಮನಿಸಿ ಮತ್ತು\nನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ನಿಜವಾದ ಬದಲಾವಣೆ ನೋಡಿ', 'home.heroAction': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ', 'home.recentActivity': 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ', 'home.emptyTitle': 'ಇನ್ನೂ ವರದಿಗಳಿಲ್ಲ', 'home.emptyMessage': 'ಗುಂಡಿ, ಕೆಟ್ಟ ಬೀದಿ ದೀಪ ಅಥವಾ ಮುಚ್ಚಿದ ಚರಂಡಿ ಕಂಡಿದ್ದೀರಾ? ವರದಿ ಮಾಡಿ, AI ಅದನ್ನು ಸರಿಯಾದ ಯೋಜನೆಗೆ ಕಳುಹಿಸುತ್ತದೆ.', 'home.emptyAction': 'ಪ್ರಾರಂಭಿಸೋಣ', 'home.errLoad': 'ನಿಮ್ಮ ವರದಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'home.processing': 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ…', 'home.channelVoice': '🎤 ಧ್ವನಿ', 'home.channelPhoto': '📷 ಫೋಟೋ', 'home.channelPhone': '☎️ ಫೋನ್',
  'newComplaint.title': 'ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ', 'newComplaint.subtitle': 'ನಿಮಗೆ ಸುಲಭವಾದ ರೀತಿಯಲ್ಲಿ ವಿವರಿಸಿ — ಉಳಿದುದನ್ನು AI ನೋಡಿಕೊಳ್ಳುತ್ತದೆ.', 'newComplaint.modeText': 'ಪಠ್ಯ', 'newComplaint.modeVoice': 'ಧ್ವನಿ', 'newComplaint.modePhoto': 'ಫೋಟೋ', 'newComplaint.problemLabel': 'ಸಮಸ್ಯೆ ಏನು?', 'newComplaint.problemPlaceholder': 'ಉದಾ: ಬಸ್ ನಿಲ್ದಾಣದ ಬಳಿ ಮುಖ್ಯ ರಸ್ತೆಯಲ್ಲಿ ದೊಡ್ಡ ಗುಂಡಿಯಿದೆ…', 'newComplaint.voiceIdle': 'ರೆಕಾರ್ಡ್ ಮಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ. ಯಾವುದೇ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ —\nಕನ್ನಡ, ತಮಿಳು ಅಥವಾ ಇಂಗ್ಲಿಷ್.', 'newComplaint.voiceRecorded': 'ರೆಕಾರ್ಡ್ ಮಾಡಲಾಗಿದೆ · {duration}', 'newComplaint.recordAgain': 'ಮತ್ತೆ ರೆಕಾರ್ಡ್ ಮಾಡಿ', 'newComplaint.takePhoto': 'ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ', 'newComplaint.choosePhoto': 'ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ', 'newComplaint.captionLabel': 'ಶೀರ್ಷಿಕೆ (ಐಚ್ಛಿಕ)', 'newComplaint.locationCaptured': 'ಸ್ಥಳ ದಾಖಲಿಸಲಾಗಿದೆ', 'newComplaint.gettingLocation': 'ಸ್ಥಳ ಪಡೆಯಲಾಗುತ್ತಿದೆ…', 'newComplaint.addLocation': 'ನಿಮ್ಮ ಸ್ಥಳ ಸೇರಿಸಿ', 'newComplaint.locationRequired': 'ಅಗತ್ಯ — ನಿಮ್ಮ ವರದಿಯನ್ನು ನಕ್ಷೆಯಲ್ಲಿ ಗುರುತಿಸುತ್ತದೆ', 'newComplaint.submit': 'ವರದಿ ಸಲ್ಲಿಸಿ', 'newComplaint.errLocationPermission': 'ಸ್ಥಳ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ', 'newComplaint.errLocation': 'ನಿಮ್ಮ ಸ್ಥಳ ಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'newComplaint.errMicPermission': 'ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ', 'newComplaint.errStartRecording': 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'newComplaint.errStopRecording': 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'newComplaint.errPickerPermission': 'ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ', 'newComplaint.errPicker': 'ಪಿಕರ್ ತೆರೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'newComplaint.errNoLocation': 'ಮೊದಲು ನಿಮ್ಮ ಸ್ಥಳ ಸೇರಿಸಿ', 'newComplaint.errNoText': 'ಮೊದಲು ಸಮಸ್ಯೆ ವಿವರಿಸಿ', 'newComplaint.errNoVoice': 'ಮೊದಲು ಧ್ವನಿ ಟಿಪ್ಪಣಿ ರೆಕಾರ್ಡ್ ಮಾಡಿ', 'newComplaint.errNoImage': 'ಮೊದಲು ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ ಅಥವಾ ಆಯ್ಕೆಮಾಡಿ', 'newComplaint.errAiBusy': 'AI ಸೇವೆ ಕಾರ್ಯನಿರತವಾಗಿದೆ. ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.', 'newComplaint.errSubmit': 'ನಿಮ್ಮ ವರದಿ ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'newComplaint.reportedAs': '{code} ಎಂದು ವರದಿ ಮಾಡಲಾಗಿದೆ', 'newComplaint.successTitle': 'ವರದಿ ಸಲ್ಲಿಸಲಾಗಿದೆ', 'newComplaint.reference': 'ಉಲ್ಲೇಖ {code}', 'newComplaint.aiAnalysis': 'AI ವಿಶ್ಲೇಷಣೆ', 'newComplaint.transcript': 'ಪ್ರತಿಲಿಪಿ', 'newComplaint.followUpTitle': 'AIಗೆ ಹೆಚ್ಚುವರಿ ಪ್ರಶ್ನೆಯಿದೆ', 'newComplaint.yourAnswer': 'ನಿಮ್ಮ ಉತ್ತರ', 'newComplaint.submitAnswer': 'ಉತ್ತರ ಸಲ್ಲಿಸಿ', 'newComplaint.refined': 'ನಿಮ್ಮ ಉತ್ತರದಿಂದ ವರದಿ ಸುಧಾರಿಸಲಾಗಿದೆ', 'newComplaint.refinedToast': 'ನಿಮ್ಮ ಉತ್ತರದಿಂದ ವರದಿ ಸುಧಾರಿಸಲಾಗಿದೆ', 'newComplaint.errFollowUp': 'ನಿಮ್ಮ ಉತ್ತರ ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'newComplaint.viewMyReports': 'ನನ್ನ ವರದಿಗಳನ್ನು ನೋಡಿ', 'newComplaint.reportAnother': 'ಮತ್ತೊಂದು ಸಮಸ್ಯೆ ವರದಿ ಮಾಡಿ',
  'menu.account': 'ಖಾತೆ', 'menu.myProfile': 'ನನ್ನ ಪ್ರೊಫೈಲ್', 'menu.privacySecurity': 'ಗೌಪ್ಯತೆ ಮತ್ತು ಭದ್ರತೆ', 'menu.privacySoon': 'ಗೌಪ್ಯತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು ಶೀಘ್ರದಲ್ಲೇ', 'menu.goToProfile': 'ಪ್ರೊಫೈಲ್ ಟ್ಯಾಬ್‌ಗೆ ಹೋಗಿ', 'menu.preferences': 'ಆದ್ಯತೆಗಳು', 'menu.darkMode': 'ಡಾರ್ಕ್ ಮೋಡ್', 'menu.lightMode': 'ಲೈಟ್ ಮೋಡ್', 'menu.language': 'ಭಾಷೆ', 'menu.logOut': 'ಲಾಗ್ ಔಟ್', 'menu.errLogout': 'ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',
  'profile.title': 'ಪ್ರೊಫೈಲ್', 'profile.citizen': 'ನಾಗರಿಕ', 'profile.authority': 'ಅಧಿಕಾರಿ', 'profile.phone': 'ಫೋನ್', 'profile.email': 'ಇಮೇಲ್', 'profile.language': 'ಭಾಷೆ', 'profile.memberSince': 'ಸದಸ್ಯರಾದ ದಿನ', 'profile.about': 'ಕುರಿತು', 'profile.aboutText': 'UCIPS ನಾಗರಿಕರ ವರದಿಗಳನ್ನು ಸಾಕ್ಷ್ಯಾಧಾರಿತ ಮೂಲಸೌಕರ್ಯ ಯೋಜನೆಗಳಾಗಿ ಪರಿವರ್ತಿಸಿ, ಪರಿಣಾಮದ ಆಧಾರದ ಮೇಲೆ ಶ್ರೇಯಾಂಕ ನೀಡುತ್ತದೆ ಮತ್ತು ಬಜೆಟ್ ಒಳಗೆ ಹಣಕಾಸನ್ನು ಉತ್ತಮಗೊಳಿಸುತ್ತದೆ.', 'profile.logOut': 'ಲಾಗ್ ಔಟ್', 'profile.logOutConfirmTitle': 'ಲಾಗ್ ಔಟ್', 'profile.logOutConfirmBody': 'ಮುಂದುವರಿಯಲು ಮತ್ತೆ ಸೈನ್ ಇನ್ ಮಾಡಬೇಕು.',
  'language.title': 'ಆಪ್ ಭಾಷೆ', 'language.subtitle': 'ಸಂಪೂರ್ಣ ಆಪ್‌ಗಾಗಿ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ.', 'language.english': 'English (ಇಂಗ್ಲಿಷ್)', 'language.tamil': 'தமிழ் (ತಮಿಳು)', 'language.hindi': 'हिन्दी (ಹಿಂದಿ)', 'language.telugu': 'తెలుగు (ತೆಲುಗು)', 'language.malayalam': 'മലയാളം (ಮಲಯಾಳಂ)', 'language.kannada': 'ಕನ್ನಡ',
  'notifications.title': 'ಅಧಿಸೂಚನೆಗಳು', 'notifications.mock1Title': 'ವರದಿ ಪರಿಹರಿಸಲಾಗಿದೆ', 'notifications.mock1Message': 'ಮುಖ್ಯ ರಸ್ತೆಯ ಕೆಟ್ಟ ಬೀದಿ ದೀಪದ ಕುರಿತು ನಿಮ್ಮ ವರದಿ ಪರಿಹರಿಸಲಾಗಿದೆ.', 'notifications.mock2Title': 'ಹೊಸ ಹಾಟ್‌ಸ್ಪಾಟ್ ಪತ್ತೆಯಾಗಿದೆ', 'notifications.mock2Message': 'ಡೌನ್‌ಟೌನ್ ಪ್ರದೇಶದಲ್ಲಿ ಪ್ರವಾಹದ ಹಲವು ವರದಿಗಳು. ಅಧಿಕಾರಿಗಳಿಗೆ ತಿಳಿಸಲಾಗಿದೆ.', 'notifications.mock3Title': 'ಯೋಜನೆ ಅನುಮೋದಿಸಲಾಗಿದೆ', 'notifications.mock3Message': 'ನಿಮ್ಮ ನೆರೆಹೊರೆಯ ರಸ್ತೆ ದುರಸ್ತಿ ಯೋಜನೆಗೆ ಬಜೆಟ್ ಅನುಮೋದಿಸಲಾಗಿದೆ.', 'notifications.time2h': '2 ಗಂಟೆಗಳ ಹಿಂದೆ', 'notifications.time5h': '5 ಗಂಟೆಗಳ ಹಿಂದೆ', 'notifications.time1d': '1 ದಿನದ ಹಿಂದೆ',
  'category.drainage': 'ಚರಂಡಿ', 'category.road': 'ರಸ್ತೆ', 'category.streetlight': 'ಬೀದಿ ದೀಪ', 'category.waste_management': 'ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ', 'category.water_supply': 'ನೀರಿನ ಪೂರೈಕೆ', 'category.sanitation': 'ನೈರ್ಮಲ್ಯ', 'category.electricity': 'ವಿದ್ಯುತ್', 'category.other': 'ಇತರೆ',
  'severity.1': 'ಸಣ್ಣ', 'severity.2': 'ಕಡಿಮೆ', 'severity.3': 'ಮಧ್ಯಮ', 'severity.4': 'ಹೆಚ್ಚು', 'severity.5': 'ಗಂಭೀರ', 'severity.unknown': 'ತಿಳಿದಿಲ್ಲ',
  'status.received': 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ', 'status.processed': 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗಿದೆ', 'status.clustered': 'ಗುಂಪುಗೊಳಿಸಲಾಗಿದೆ', 'status.in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ', 'status.resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ', 'status.open': 'ತೆರೆದಿದೆ', 'status.validated': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ', 'status.actioned': 'ಕ್ರಮ ಕೈಗೊಳ್ಳಲಾಗಿದೆ', 'status.candidate': 'ಪ್ರಸ್ತಾವಿತ', 'status.selected': 'ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ', 'status.approved': 'ಅನುಮೋದಿಸಲಾಗಿದೆ', 'status.rejected': 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ', 'status.draft': 'ಕರಡು',
  'common.reports': 'ವರದಿಗಳು', 'common.report': 'ವರದಿ', 'common.people': 'ಜನರು', 'common.kmAway': '{distance} ಕಿ.ಮೀ ದೂರ', 'common.locationOff': 'ಸ್ಥಳ ಆಫ್ ಆಗಿದೆ — ದೂರದ ಬದಲು ಬೇಡಿಕೆಯ ಆಧಾರದ ಮೇಲೆ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತಿದೆ.', 'common.list': 'ಪಟ್ಟಿ', 'common.map': 'ನಕ್ಷೆ', 'common.close': 'ಮುಚ್ಚಿ', 'common.viewComplaints': 'ದೂರುಗಳನ್ನು ನೋಡಿ', 'common.ai': 'AI', 'common.text': 'ಪಠ್ಯ', 'common.voice': 'ಧ್ವನಿ', 'common.photo': 'ಫೋಟೋ', 'common.phone': 'ಫೋನ್', 'common.location': 'ಸ್ಥಳ', 'common.goBack': 'ಹಿಂದೆ ಹೋಗಿ',
  'detail.complaint': 'ದೂರು', 'detail.aiSummary': 'AI ಸಾರಾಂಶ', 'detail.trackTitle': 'ಪ್ರಗತಿ ಗಮನಿಸಿ', 'detail.whatYouSaid': 'ನೀವು ಹೇಳಿದ್ದು', 'detail.yourWords': 'ನಿಮ್ಮ ಮಾತುಗಳು', 'detail.yourFeedback': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆ', 'detail.rateResolution': 'ಪರಿಹಾರವನ್ನು ರೇಟ್ ಮಾಡಿ', 'detail.commentOptional': 'ಟಿಪ್ಪಣಿ (ಐಚ್ಛಿಕ)', 'detail.submitFeedback': 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಿ', 'detail.thanksFeedback': 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಗೆ ಧನ್ಯವಾದಗಳು', 'detail.alreadyReviewed': 'ಈ ವರದಿಯನ್ನು ನೀವು ಈಗಾಗಲೇ ಪರಿಶೀಲಿಸಿದ್ದೀರಿ', 'detail.feedbackError': 'ಪ್ರತಿಕ್ರಿಯೆ ಸಲ್ಲಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'detail.loadError': 'ಈ ವರದಿ ಲೋಡ್ ಆಗಲಿಲ್ಲ',
  'nearby.title': 'ಸಮೀಪದಲ್ಲಿ', 'nearby.subtitle': 'ನಿಮ್ಮ ನೆರೆಹೊರೆಯವರು ವರದಿ ಮಾಡಿರುವುದು', 'nearby.noHotspotsTitle': 'ಇನ್ನೂ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳಿಲ್ಲ', 'nearby.noHotspotsMessage': 'ಹಲವು ಸಮೀಪದ ವರದಿಗಳು ಒಂದೇ ಸಮಸ್ಯೆಯನ್ನು ಸೂಚಿಸಿದಾಗ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.', 'nearby.reports': 'ವರದಿಗಳು', 'nearby.communityDemand': 'ಸಮುದಾಯದ ಬೇಡಿಕೆ', 'nearby.loadError': 'ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'hotspots.title': 'ಬೇಡಿಕೆ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು', 'hotspots.subtitle': 'ಬೇಡಿಕೆಯ ಆಧಾರದ ಮೇಲೆ ಕ್ರಮಗೊಳಿಸಿದ ನಾಗರಿಕ ವರದಿಗಳು', 'hotspots.statHotspots': 'ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು', 'hotspots.statReports': 'ವರದಿಗಳು', 'hotspots.statTopDemand': 'ಅತಿ ಹೆಚ್ಚು ಬೇಡಿಕೆ', 'hotspots.demandScore': 'ಬೇಡಿಕೆ ಸ್ಕೋರ್', 'hotspots.noHotspotsMessage': 'ಸಾಕಷ್ಟು ಸಮೀಪದ ವರದಿಗಳು ಒಂದೇ ವರ್ಗವನ್ನು ಹಂಚಿಕೊಂಡಾಗ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು ರೂಪುಗೊಳ್ಳುತ್ತವೆ.', 'hotspots.loadError': 'ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',
  'reports.title': 'ಎಲ್ಲಾ ವರದಿಗಳು', 'reports.subtitle': 'ಗುಂಪುಗೊಳಿಸಿದರೂ ಇಲ್ಲದಿದ್ದರೂ ಎಲ್ಲಾ ನಾಗರಿಕ ವರದಿಗಳು', 'reports.total': 'ಒಟ್ಟು', 'reports.inHotspots': 'ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳಲ್ಲಿ', 'reports.processed': 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗಿದೆ', 'reports.emptyTitle': 'ಇನ್ನೂ ವರದಿಗಳಿಲ್ಲ', 'reports.emptyMessage': 'ನಾಗರಿಕರು ಸಲ್ಲಿಸುವ ವರದಿಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.', 'reports.loadError': 'ವರದಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',
  'projects.title': 'ಕ್ರಮಾಂಕಿತ ಯೋಜನೆಗಳು', 'projects.subtitle': 'AI ರಚಿಸಿದ, ಸ್ಕೋರ್ ಮತ್ತು ವಿವರಣೆಯೊಂದಿಗೆ ಯೋಜನೆಗಳು', 'projects.totalAsk': 'ಒಟ್ಟು ಅಗತ್ಯ', 'projects.people': 'ಜನರು', 'projects.emptyTitle': 'ಇನ್ನೂ ಯೋಜನೆಗಳಿಲ್ಲ', 'projects.emptyMessage': 'ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳು ರೂಪಗೊಂಡು ಸಾಕ್ಷ್ಯ ಪರಿಶೀಲನೆ ಮುಗಿದ ನಂತರ ಯೋಜನೆಗಳು ರಚನೆಯಾಗುತ್ತವೆ.', 'projects.loadError': 'ಯೋಜನೆಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'projects.priority': 'ಆದ್ಯತೆ', 'projects.cost': 'ವೆಚ್ಚ', 'projects.beneficiaries': 'ಫಲಾನುಭವಿಗಳು', 'projects.demand': 'ಬೇಡಿಕೆ', 'projects.impact': 'ಪರಿಣಾಮ', 'projects.urgency': 'ತುರ್ತು', 'projects.feasibility': 'ಸಾಧ್ಯತೆ', 'projects.whyRanking': 'ಈ ಕ್ರಮಾಂಕ ಏಕೆ?', 'projects.hideReasoning': 'AI ಕಾರಣ ಮರೆಮಾಡಿ',
  'budget.title': 'ಬಜೆಟ್ ಆಪ್ಟಿಮೈಸರ್', 'budget.subtitle': 'ಕ್ರಮಾಂಕಿತ ಯೋಜನೆಗಳ ಮೇಲೆ 0/1 knapsack — ಪ್ರತಿ ರೂಪಾಯಿಗೆ ಗರಿಷ್ಠ ಪರಿಣಾಮ', 'budget.available': 'ಲಭ್ಯವಿರುವ ಬಜೆಟ್ (₹)', 'budget.run': 'ಆಪ್ಟಿಮೈಸೇಶನ್ ನಡೆಸಿ', 'budget.enterAmount': 'ಮೊದಲು ಬಜೆಟ್ ಮೊತ್ತ ನಮೂದಿಸಿ', 'budget.authorityOnly': 'ಅಧಿಕಾರಿ ಖಾತೆಗಳು ಮಾತ್ರ ಆಪ್ಟಿಮೈಸರ್ ನಡೆಸಬಹುದು', 'budget.error': 'ಆಪ್ಟಿಮೈಸರ್ ನಡೆಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'budget.expectedImpact': 'ನಿರೀಕ್ಷಿತ ಪರಿಣಾಮ', 'budget.allocated': 'ಹಂಚಿಕೆ ಮಾಡಲಾಗಿದೆ', 'budget.selected': 'ಆಯ್ಕೆಮಾಡಲಾಗಿದೆ', 'budget.draft': 'ಕರಡು', 'budget.approved': 'ಅನುಮೋದಿಸಲಾಗಿದೆ', 'budget.utilised': 'ಬಜೆಟ್‌ನ {percent}% ಬಳಸಲಾಗಿದೆ', 'budget.approve': 'ಈ ಹಂಚಿಕೆಯನ್ನು ಅನುಮೋದಿಸಿ', 'budget.approveSuccess': 'ಬಜೆಟ್ ಅನುಮೋದಿಸಲಾಗಿದೆ — ಯೋಜನೆಗಳಿಗೆ ಹಣ ದೊರಕಿದೆ', 'budget.approveError': 'ಈ ರನ್ ಅನುಮೋದಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'budget.alreadyApproved': 'ಈ ರನ್ ಈಗಾಗಲೇ ಅನುಮೋದಿಸಲಾಗಿದೆ', 'budget.funded': 'ಹಣ ಒದಗಿಸಲಾಗಿದೆ', 'budget.notFunded': 'ಹಣ ಒದಗಿಸಿಲ್ಲ',
  'hotspotDetail.evidence': 'ಮೂಲ ಸಾಕ್ಷ್ಯ', 'hotspotDetail.noComplaints': 'ದೂರುಗಳಿಲ್ಲ', 'hotspotDetail.noComplaintsMessage': 'ಈ ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗೆ ಯಾವುದೇ ವರದಿಗಳು ಜೋಡಿಸಲ್ಪಟ್ಟಿಲ್ಲ.', 'hotspotDetail.loadError': 'ದೂರುಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ', 'map.loading': 'ನಕ್ಷೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ…', 'map.offline': 'ನಕ್ಷೆಗೆ ಇಂಟರ್ನೆಟ್ ಸಂಪರ್ಕ ಅಗತ್ಯವಿದೆ', 'map.switchList': 'ಹಾಟ್‌ಸ್ಪಾಟ್‌ಗಳನ್ನು ನೋಡಲು ಪಟ್ಟಿ ವೀಕ್ಷಣೆಗೆ ಬದಲಾಯಿಸಿ',
};
